org.gradle.internal.http.connectionTimeout=60000
org.gradle.internal.http.socketTimeout=60000
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
//MAPBOX_DOWNLOADS_TOKEN=sk.eyJ1IjoidHJhZGViYXIiLCJhIjoiY2x6OGE1dHVrMDB5NTJscXE1ZGpuMzVoayJ9.eE5nDO7q3r4rrD1GGsNGqw

MAPBOX_DOWNLOADS_TOKEN=sk.eyJ1IjoidHJhZGViYXIiLCJhIjoiY2x6ZmUydmo4MHo3ODJxczlqMjdhZHBtbyJ9.wbAxq1iDjmsvHRXftCnBZw
